### ISSUE TITLE
Cannot auto update

### ISSUE THREAD

**Issue by gabmontes** [autonomoussoftware/metronome-wallet-desktop#317]
Error thrown when opening the wallet:

```
Unhandled Promise Rejection
Error: Could not get code signature for running application
    at Server.<anonymous> (/Applications/Metronome Wallet.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:85:28)
From previous event:
    at /Applications/Metronome Wallet.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:44:12
From previous event:
    at MacUpdater.doDownloadUpdate (/Applications/Metronome Wallet.app/Contents/Resources/app.asar/node_modules/electron-updater/out/MacUpdater.js:127:11)
    at /Applications/Metronome Wallet.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:340:25
    at Generator.next (<anonymous>)
From previous event:
    at MacUpdater.downloadUpdate (/Applications/Metronome Wallet.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:382:11)
    at /Applications/Metronome Wallet.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:316:49
From previous event:
    at MacUpdater.doCheckForUpdates (/Applications/Metronome Wallet.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:353:11)
    at /Applications/Metronome Wallet.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:264:25
    at Generator.next (<anonymous>)
From previous event:
    at MacUpdater._checkForUpdates (/Applications/Metronome Wallet.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:307:11)
    at MacUpdater.checkForUpdates (/Applications/Metronome Wallet.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:213:35)
    at initAutoUpdate (/Applications/Metronome Wallet.app/Contents/Resources/app.asar/build/main/mainWindow.js:41:15)
    at App.loadWindow (/Applications/Metronome Wallet.app/Contents/Resources/app.asar/build/main/mainWindow.js:95:3)
```

**Comment by ianaya89** [comment]
Resolved
