### ISSUE TITLE
Add recover wallet option on login screen

### ISSUE THREAD

**Issue by ianaya89** [autonomoussoftware/metronome-wallet-desktop#321]

**Comment by jsager1** [comment]
Has this been implemented yet?  I'm locked out of the damn wallet and can't get in.  Is there a workaround?

thanks,
Jim

**Comment by ianaya89** [comment]
Hi Jim, we are still working on this.
What you can do is to manually remove settings file.

Then you open again the wallet, set a new password and  restore your
previous wallet. Take in mind that you need your mnemonic.

Which OS are you using?

**Comment by jsager1** [comment]
Hi Ignacio,

Thanks for the quick response, 
I’m using Win7 Ultimate.  Yes I do have my initial pass phrase that I saved.
Where/which settings file do I need to remove?
Thanks.

**Comment by ianaya89** [comment]
No problem. So, the file should be located at
~/AppData/Roaming/metronome-desktop-wallet/Settings`

Let me know if this works.

**Comment by jsager1** [comment]
Yep,,, I found it,,, saved to settings-old then deleted the original .
Worked like a champ,,,, I’m back in my wallet.

Thanks Ignacio.

**Comment by HelionGroup** [comment]
Ignacio, I have the same issue with macOS.  Where would I remove the setting from?

**Comment by ianaya89** [comment]
Hey, the Settings file in macOS is located at:
`~/Library/Application Support/metronome-desktop-wallet/Settings`

**Comment by HelionGroup** [comment]
TY.  I'm not sure why I don't see that folder after re-installing.

**Comment by ianaya89** [comment]
Did it work? Which is the folder that you are not seeing?

**Comment by HelionGroup** [comment]
metronome-desktop-wallet/Settings - this folder does not appear.

It worked the first time and I made an ETH transfer, but I am locked out and there is no metronome file visible except the app.

**Comment by ianaya89** [comment]
Can you confirm that you are in the correct path? This is the complete path: `~/Library/Application\ Support/metronome-desktop-wallet/Settings`

Take in mind that Settings is not a folder, is the file that you need to remove.

**Comment by HelionGroup** [comment]
<img width="874" alt="screen shot 2018-06-23 at 11 54 33 am" src="https://user-images.githubusercontent.com/27436158/41811377-70a720e4-76dc-11e8-9b1e-76ea400b1aaa.png">

**Comment by gabmontes** [comment]
@HelionGroup the `Library` folder you have to look for is within your home folder (`~`), not in root (`/`).

All settings files are documented in the README too: https://github.com/autonomoussoftware/metronome-wallet-desktop#development-notes

**Comment by HelionGroup** [comment]
If I type into Terminal
rm ~/Library/Application\ Support/metronome-desktop-wallet/Settings

I receive "no file found"

I also receive err msgs:

Unhandled Error
TypeError: Cannot read property 'toLowerCase' of undefined
    at getAuctionAddress (/Applications/Metronome Wallet.app/Contents/Resources/app.asar/build/main/plugins/metronome/settings.js:6:47)
    at sendStatus (/Applications/Metronome Wallet.app/Contents/Resources/app.asar/build/main/plugins/metronome/status.js:19:54)
    at /Applications/Metronome Wallet.app/Contents/Resources/app.asar/build/main/plugins/metronome/index.js:25:5
    at Array.forEach (<anonymous>)
    at /Applications/Metronome Wallet.app/Contents/Resources/app.asar/build/main/plugins/metronome/index.js:24:17
    at EventEmitter.<anonymous> (/Applications/Metronome Wallet.app/Contents/Resources/app.asar/build/main/base-plugin.js:55:7)
    at EventEmitter.<anonymous> (/Applications/Metronome Wallet.app/Contents/Resources/app.asar/build/main/plugins/metronome/index.js:19:20)
    at EventEmitter.eventsBus.emit (/Applications/Metronome Wallet.app/Contents/Resources/app.asar/build/main/main-worker.js:55:5)
    at Socket.<anonymous> (/Applications/Metronome Wallet.app/Contents/Resources/app.asar/build/main/plugins/bloq-eth-explorer/index.js:58:17)
    at Socket.Emitter.emit (/Applications/Metronome Wallet.app/Contents/Resources/app.asar/node_modules/component-emitter/index.js:133:20)
    at Socket.onevent (/Applications/Metronome Wallet.app/Contents/Resources/app.asar/node_modules/socket.io-client/lib/socket.js:270:10)
    at Socket.onpacket (/Applications/Metronome Wallet.app/Contents/Resources/app.asar/node_modules/socket.io-client/lib/socket.js:228:12)
    at Manager.<anonymous> (/Applications/Metronome Wallet.app/Contents/Resources/app.asar/node_modules/component-bind/index.js:21:15)
    at Manager.Emitter.emit (/Applications/Metronome Wallet.app/Contents/Resources/app.asar/node_modules/component-emitter/index.js:133:20)
    at Manager.ondecoded (/Applications/Metronome Wallet.app/Contents/Resources/app.asar/node_modules/socket.io-client/lib/manager.js:345:8)
    at Decoder.<anonymous> (/Applications/Metronome Wallet.app/Contents/Resources/app.asar/node_modules/component-bind/index.js:21:15)
    at Decoder.Emitter.emit (/Applications/Metronome Wallet.app/Contents/Resources/app.asar/node_modules/component-emitter/index.js:133:20)
    at Decoder.add (/Applications/Metronome Wallet.app/Contents/Resources/app.asar/node_modules/socket.io-parser/index.js:242:12)
    at Manager.ondata (/Applications/Metronome Wallet.app/Contents/Resources/app.asar/node_modules/socket.io-client/lib/manager.js:335:16)
    at Socket.<anonymous> (/Applications/Metronome Wallet.app/Contents/Resources/app.asar/node_modules/component-bind/index.js:21:15)
    at Socket.Emitter.emit (/Applications/Metronome Wallet.app/Contents/Resources/app.asar/node_modules/component-emitter/index.js:133:20)
    at Socket.onPacket (/Applications/Metronome Wallet.app/Contents/Resources/app.asar/node_modules/engine.io-client/lib/socket.js:456:14)
    at WS.<anonymous> (/Applications/Metronome Wallet.app/Contents/Resources/app.asar/node_modules/engine.io-client/lib/socket.js:273:10)
    at WS.Emitter.emit (/Applications/Metronome Wallet.app/Contents/Resources/app.asar/node_modules/component-emitter/index.js:133:20)
    at WS.Transport.onPacket (/Applications/Metronome Wallet.app/Contents/Resources/app.asar/node_modules/engine.io-client/lib/transport.js:145:8)
    at WS.Transport.onData (/Applications/Metronome Wallet.app/Contents/Resources/app.asar/node_modules/engine.io-client/lib/transport.js:137:8)
    at WebSocket.ws.onmessage (/Applications/Metronome Wallet.app/Contents/Resources/app.asar/node_modules/engine.io-client/lib/transports/websocket.js:147:10)
    at WebSocket.onMessage (/Applications/Metronome Wallet.app/Contents/Resources/app.asar/node_modules/ws/lib/EventTarget.js:99:16)
    at Receiver._receiver.onmessage (/Applications/Metronome Wallet.app/Contents/Resources/app.asar/node_modules/ws/lib/WebSocket.js:141:47)
    at Receiver.dataMessage (/Applications/Metronome Wallet.app/Contents/Resources/app.asar/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (/Applications/Metronome Wallet.app/Contents/Resources/app.asar/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/Applications/Metronome Wallet.app/Contents/Resources/app.asar/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/Applications/Metronome Wallet.app/Contents/Resources/app.asar/node_modules/ws/lib/Receiver.js:139:10)
    at TLSSocket._ultron.on (/Applications/Metronome Wallet.app/Contents/Resources/app.asar/node_modules/ws/lib/WebSocket.js:138:22)

**Comment by HelionGroup** [comment]
is there a way to find those settings without using Terminal? through Finder?

**Comment by HelionGroup** [comment]
NM, found it.
