### ISSUE TITLE
Error: while converting number to string, invalid number value '2,5', should be a number matching (^-?[0...

### ISSUE THREAD

**Issue by gabmontes** [autonomoussoftware/metronome-wallet-desktop#369]
https://sentry.io/bloq-inc/metronome-desktop-wallet/issues/589191482/

```
Error: while converting number to string, invalid number value '2,5', should be a number matching (^-?[0-9.]+).
  at i (/Applications/Metronome%20Wallet.app/Contents/Resources/app.asar/build/static/js/main.e5847f9c.js:1:810791)
  at Object.a [as toWei] (/Applications/Metronome%20Wallet.app/Contents/Resources/app.asar/build/static/js/main.e5847f9c.js:1:811530)
  at Object.p [as toWei] (/Applications/Metronome%20Wallet.app/Contents/Resources/app.asar/build/static/js/main.e5847f9c.js:1:121270)
  at Object.a.renderConfirmation (/Applications/Metronome%20Wallet.app/Contents/Resources/app.asar/build/static/js/main.e5847f9c.js:1:1879199)
  at t.value (/Applications/Metronome%20Wallet.app/Contents/Resources/app.asar/build/static/js/main.e5847f9c.js:1:230421)
...
(11 additional frame(s) were not displayed)
```

**Comment by gabmontes** [comment]
Sentry issue: [METRONOME-DESKTOP-WALLET-51](https://sentry.io/bloq-inc/metronome-desktop-wallet/issues/589114275/)

**Comment by gabmontes** [comment]
Sentry issue: [METRONOME-DESKTOP-WALLET-3A](https://sentry.io/bloq-inc/metronome-desktop-wallet/issues/587307734/)

**Comment by gabmontes** [comment]
Sentry issue: [METRONOME-DESKTOP-WALLET-5E](https://sentry.io/bloq-inc/metronome-desktop-wallet/issues/589160895/)

**Comment by gabmontes** [comment]
Sentry issue: [METRONOME-DESKTOP-WALLET-5J](https://sentry.io/bloq-inc/metronome-desktop-wallet/issues/589171619/)

**Comment by gabmontes** [comment]
Sentry issue: [METRONOME-DESKTOP-WALLET-52](https://sentry.io/bloq-inc/metronome-desktop-wallet/issues/589114373/)

**Comment by gabmontes** [comment]
Sentry issue: [METRONOME-DESKTOP-WALLET-3Y](https://sentry.io/bloq-inc/metronome-desktop-wallet/issues/588776674/)
