### ISSUE TITLE
First time I run the app, it crashes.

### ISSUE THREAD

**Issue by martincarrera** [autonomoussoftware/metronome-wallet-desktop#405]
When I run the app for the first time it crashes with error `ENOENT no such file or directory...`

After first crash, the application no longer crashes with that error.

**Comment by jcvernaleo** [comment]
I just hit this too on osx with 1.1.5.  I'm guessing it needs to make `$USER/Library/Application Support/metronome-desktop-wallet/Settings` immediately so it is there when it first looks for it.

**Comment by pablen** [comment]
Confirm same issue on Windows build.

Complete log below

```
[1] App threw an error during load
[1] Error: ENOENT: no such file or directory, open '/Users/pablo/Library/Application Support/metronome-desktop-wallet/Settings'
[1]     at Object.fs.openSync (fs.js:652:18)
[1]     at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:172:20)
[1]     at Object.fs.writeFileSync (fs.js:1311:33)
[1]     at Object.writeFileSync (/Users/pablo/code/bloq/metronome-wallet-desktop/node_modules/jsonfile/index.js:117:13)
[1]     at Settings._ensureSettings (/Users/pablo/code/bloq/metronome-wallet-desktop/node_modules/electron-settings/lib/settings.js:153:18)
[1]     at Settings._readSettings (/Users/pablo/code/bloq/metronome-wallet-desktop/node_modules/electron-settings/lib/settings.js:192:10)
[1]     at Settings._getValueAtKeyPath (/Users/pablo/code/bloq/metronome-wallet-desktop/node_modules/electron-settings/lib/settings.js:281:22)
[1]     at Settings.get (/Users/pablo/code/bloq/metronome-wallet-desktop/node_modules/electron-settings/lib/settings.js:404:17)
[1]     at Object.<anonymous> (/Users/pablo/code/bloq/metronome-wallet-desktop/public/analytics.js:9:29)
[1]     at Object.<anonymous> (/Users/pablo/code/bloq/metronome-wallet-desktop/public/analytics.js:37:3)
[1]     at Module._compile (module.js:569:30)
[1]     at Object.Module._extensions..js (module.js:580:10)
[1]     at Module.load (module.js:503:32)
[1]     at tryModuleLoad (module.js:466:12)
[1]     at Function.Module._load (module.js:458:3)
[1]     at Module.require (module.js:513:17)
[1]     at require (internal/module.js:11:18)
[1]     at Object.<anonymous> (/Users/pablo/code/bloq/metronome-wallet-desktop/public/main/main-window.js:9:19)
[1]     at Object.<anonymous> (/Users/pablo/code/bloq/metronome-wallet-desktop/public/main/main-window.js:110:3)
[1]     at Module._compile (module.js:569:30)
[1]     at Object.Module._extensions..js (module.js:580:10)
[1]     at Module.load (module.js:503:32)
[1]     at tryModuleLoad (module.js:466:12)
[1]     at Function.Module._load (module.js:458:3)
[1]     at Module.require (module.js:513:17)
[1]     at require (internal/module.js:11:18)
[1]     at Object.<anonymous> (/Users/pablo/code/bloq/metronome-wallet-desktop/public/electron.js:52:26)
[1]     at Object.<anonymous> (/Users/pablo/code/bloq/metronome-wallet-desktop/public/electron.js:64:3)
[1]     at Module._compile (module.js:569:30)
[1]     at Object.Module._extensions..js (module.js:580:10)
[1]     at Module.load (module.js:503:32)
[1]     at tryModuleLoad (module.js:466:12)
[1]     at Function.Module._load (module.js:458:3)
[1]     at loadApplicationPackage (/Users/pablo/code/bloq/metronome-wallet-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:287:12)
[1]     at Object.<anonymous> (/Users/pablo/code/bloq/metronome-wallet-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:329:5)
[1]     at Object.<anonymous> (/Users/pablo/code/bloq/metronome-wallet-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:366:3)
[1]     at Module._compile (module.js:569:30)
[1]     at Object.Module._extensions..js (module.js:580:10)
[1]     at Module.load (module.js:503:32)
[1]     at tryModuleLoad (module.js:466:12)
[1]     at Function.Module._load (module.js:458:3)
[1]     at Object.<anonymous> (/Users/pablo/code/bloq/metronome-wallet-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/init.js:171:8)
[1]     at Object.<anonymous> (/Users/pablo/code/bloq/metronome-wallet-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/init.js:173:3)
[1]     at Module._compile (module.js:569:30)
[1]     at Object.Module._extensions..js (module.js:580:10)
[1]     at Module.load (module.js:503:32)
[1]     at tryModuleLoad (module.js:466:12)
[1]     at Function.Module._load (module.js:458:3)
[1]     at Function.Module.runMain (module.js:605:10)
[1]     at startup (bootstrap_node.js:167:16)
[1]     at bootstrap_node.js:589:3
[1] 2018-11-14T17:16:36.537Z - error:	Error: ENOENT: no such file or directory, open '/Users/pablo/Library/Application Support/metronome-desktop-wallet/Settings'
```
