### ISSUE TITLE
Cloned the wallet locally, installed npm, node and dependancies but get connect error

### ISSUE THREAD

**Issue by GetITWorking** [autonomoussoftware/metronome-wallet-desktop#478]
Have not changed any code as yet, was hoping to fix connection issue, but cant get the app to connect to my Wallete get the following error :

```
[1] 2021-02-15T20:39:50.155Z met-wallet:core <<-- wallet-error { inner:
[1]    Error: connection not open
[1]        at WebsocketProvider.send (/home/aled/git/metronome-wallet-desktop/node_modules/web3-providers-ws/src/index.js:294:18)
[1]        at RequestManager.send (/home/aled/git/metronome-wallet-desktop/node_modules/web3-core-requestmanager/src/index.js:135:66)
[1]        at sendRequest (/home/aled/git/metronome-wallet-desktop/node_modules/web3-core-method/src/index.js:570:42)
[1]        at Eth.send [as getBalance] (/home/aled/git/metronome-wallet-desktop/node_modules/web3-core-method/src/index.js:591:13)
[1]        at emitBalance (/home/aled/git/metronome-wallet-desktop/node_modules/metronome-wallet-core/src/plugins/wallet/index.js:19:16)
[1]        at EventEmitter.<anonymous> (/home/aled/git/metronome-wallet-desktop/node_modules/metronome-wallet-core/src/plugins/wallet/index.js:43:7)
[1]        at EventEmitter.emit (events.js:199:15)
[1]        at EventEmitter.emit (domain.js:469:20)
[1]        at EventEmitter.eventBus.emit (/home/aled/git/metronome-wallet-desktop/node_modules/metronome-wallet-core/src/index.js:37:9)
[1]        at /home/aled/git/metronome-wallet-desktop/public/main/client/handlers/single-core.js:37:13
[1]        at Array.forEach (<anonymous>)
[1]        at openWallet (/home/aled/git/metronome-wallet-desktop/public/main/client/handlers/single-core.js:36:48)
[1]        at Array.forEach (<anonymous>)
[1]        at /home/aled/git/metronome-wallet-desktop/public/main/client/handlers/multi-core.js:50:11,
[1]   message: 'Could not get ETH balance',
[1]   meta: { plugin: 'wallet' } }
[1] 2021-02-15T20:39:50.157Z met-wallet:core <<-- wallet-error { inner:
[1]    Error: connection not open
[1]        at WebsocketProvider.send (/home/aled/git/metronome-wallet-desktop/node_modules/web3-providers-ws/src/index.js:294:18)
[1]        at RequestManager.send (/home/aled/git/metronome-wallet-desktop/node_modules/web3-core-requestmanager/src/index.js:135:66)
[1]        at sendRequest (/home/aled/git/metronome-wallet-desktop/node_modules/web3-core-method/src/index.js:570:42)
[1]        at send (/home/aled/git/metronome-wallet-desktop/node_modules/web3-core-method/src/index.js:591:13)
[1]        at Object._executeMethod (/home/aled/git/metronome-wallet-desktop/node_modules/web3-eth-contract/src/index.js:826:24)
[1]        at getTokenBalance (/home/aled/git/metronome-wallet-desktop/node_modules/metronome-wallet-core/src/plugins/tokens/index.js:37:48)
[1]        at /home/aled/git/metronome-wallet-desktop/node_modules/metronome-wallet-core/src/plugins/tokens/index.js:57:9
[1]        at Array.forEach (<anonymous>)
[1]        at emitBalances (/home/aled/git/metronome-wallet-desktop/node_modules/metronome-wallet-core/src/plugins/tokens/index.js:56:14)
[1]        at EventEmitter.<anonymous> (/home/aled/git/metronome-wallet-desktop/node_modules/metronome-wallet-core/src/plugins/tokens/index.js:88:7)
[1]        at EventEmitter.emit (events.js:199:15)
[1]        at EventEmitter.emit (domain.js:469:20)
[1]        at EventEmitter.eventBus.emit (/home/aled/git/metronome-wallet-desktop/node_modules/metronome-wallet-core/src/index.js:37:9)
[1]        at /home/aled/git/metronome-wallet-desktop/public/main/client/handlers/single-core.js:37:13
[1]        at Array.forEach (<anonymous>)
[1]        at openWallet (/home/aled/git/metronome-wallet-desktop/public/main/client/handlers/single-core.js:36:48)
[1]        at Array.forEach (<anonymous>)
[1]        at /home/aled/git/metronome-wallet-desktop/public/main/client/handlers/multi-core.js:50:11,
[1]   message: 'Could not get MET token balance',
[1]   meta: { plugin: 'tokens' } }
[1] 2021-02-15T20:39:50.157Z - verbose:	<-- wallet-error {"inner":{},"message":"Could not get ETH balance","meta":{"plugin":"wallet"},"chain":"ethRopsten"}	
[1] 2021-02-15T20:39:50.157Z - warn:	Could not get ETH balance - connection not open	
[1] 2021-02-15T20:39:50.159Z - verbose:	<-- wallet-error {"inner":{},"message":"Could not get MET token balance","meta":{"plugin":"tokens"},"chain":"ethRopsten"}	
[1] 2021-02-15T20:39:50.159Z - warn:	Could not get MET token balance - connection not open	
[1] 2021-02-15T20:39:50.160Z - verbose:	<-- wallet-error {"inner":{},"message":"Could not get ETC balance","meta":{"plugin":"wallet"},"chain":"etcMordor"}	
[1] 2021-02-15T20:39:50.160Z - warn:	Could not get ETC balance - connection not open	
[1] 2021-02-15T20:39:50.161Z - verbose:	<-- wallet-error {"inner":{},"message":"Could not get MET token balance","meta":{"plugin":"tokens"},"chain":"etcMordor"}	
[1] 2021-02-15T20:39:50.161Z - warn:	Could not get MET token balance - connection not open	
[1] 2021-02-15T20:39:50.159Z met-wallet:core <<-- wallet-error { inner:
[1]    Error: connection not open
[1]        at WebsocketProvider.send (/home/aled/git/metronome-wallet-desktop/node_modules/web3-providers-ws/src/index.js:294:18)
[1]        at RequestManager.send (/home/aled/git/metronome-wallet-desktop/node_modules/web3-core-requestmanager/src/index.js:135:66)
[1]        at sendRequest (/home/aled/git/metronome-wallet-desktop/node_modules/web3-core-method/src/index.js:570:42)
[1]        at Eth.send [as getBalance] (/home/aled/git/metronome-wallet-desktop/node_modules/web3-core-method/src/index.js:591:13)
[1]        at emitBalance (/home/aled/git/metronome-wallet-desktop/node_modules/metronome-wallet-core/src/plugins/wallet/index.js:19:16)
[1]        at EventEmitter.<anonymous> (/home/aled/git/metronome-wallet-desktop/node_modules/metronome-wallet-core/src/plugins/wallet/index.js:43:7)
[1]        at EventEmitter.emit (events.js:199:15)
[1]        at EventEmitter.emit (domain.js:469:20)
[1]        at EventEmitter.eventBus.emit (/home/aled/git/metronome-wallet-desktop/node_modules/metronome-wallet-core/src/index.js:37:9)
[1]        at /home/aled/git/metronome-wallet-desktop/public/main/client/handlers/single-core.js:37:13
[1]        at Array.forEach (<anonymous>)
[1]        at openWallet (/home/aled/git/metronome-wallet-desktop/public/main/client/handlers/single-core.js:36:48)
[1]        at Array.forEach (<anonymous>)
[1]        at /home/aled/git/metronome-wallet-desktop/public/main/client/handlers/multi-core.js:50:11,
[1]   message: 'Could not get ETC balance',
[1]   meta: { plugin: 'wallet' } }
[1] 2021-02-15T20:39:50.160Z met-wallet:core <<-- wallet-error { inner:
[1]    Error: connection not open
[1]        at WebsocketProvider.send (/home/aled/git/metronome-wallet-desktop/node_modules/web3-providers-ws/src/index.js:294:18)
[1]        at RequestManager.send (/home/aled/git/metronome-wallet-desktop/node_modules/web3-core-requestmanager/src/index.js:135:66)
[1]        at sendRequest (/home/aled/git/metronome-wallet-desktop/node_modules/web3-core-method/src/index.js:570:42)
[1]        at send (/home/aled/git/metronome-wallet-desktop/node_modules/web3-core-method/src/index.js:591:13)
[1]        at Object._executeMethod (/home/aled/git/metronome-wallet-desktop/node_modules/web3-eth-contract/src/index.js:826:24)
[1]        at getTokenBalance (/home/aled/git/metronome-wallet-desktop/node_modules/metronome-wallet-core/src/plugins/tokens/index.js:37:48)
[1]        at /home/aled/git/metronome-wallet-desktop/node_modules/metronome-wallet-core/src/plugins/tokens/index.js:57:9
[1]        at Array.forEach (<anonymous>)
[1]        at emitBalances (/home/aled/git/metronome-wallet-desktop/node_modules/metronome-wallet-core/src/plugins/tokens/index.js:56:14)
[1]        at EventEmitter.<anonymous> (/home/aled/git/metronome-wallet-desktop/node_modules/metronome-wallet-core/src/plugins/tokens/index.js:88:7)
[1]        at EventEmitter.emit (events.js:199:15)
[1]        at EventEmitter.emit (domain.js:469:20)
[1]        at EventEmitter.eventBus.emit (/home/aled/git/metronome-wallet-desktop/node_modules/metronome-wallet-core/src/index.js:37:9)
[1]        at /home/aled/git/metronome-wallet-desktop/public/main/client/handlers/single-core.js:37:13
[1]        at Array.forEach (<anonymous>)
[1]        at openWallet (/home/aled/git/metronome-wallet-desktop/public/main/client/handlers/single-core.js:36:48)
[1]        at Array.forEach (<anonymous>)
[1]        at /home/aled/git/metronome-wallet-desktop/public/main/client/handlers/multi-core.js:50:11,
[1]   message: 'Could not get MET token balance',
[1]   meta: { plugin: 'tokens' } }
[1] 2021-02-15T20:39:50.229Z - verbose:	<-- transactions-scan-started {"chain":"ethRopsten"}	
[1] 2021-02-15T20:39:50.231Z - verbose:	<-- transactions-scan-started {"chain":"etcMordor"}	
[1] 2021-02-15T20:39:51.723Z met-wallet:core:eth:web3 Web3 provider connection error error
[1] 2021-02-15T20:39:51.724Z met-wallet:core <<-- web3-connection-status-changed { connected: false }
```

Not familar to ReactNative, so is there anything im missing?

any help will be great

Cheers

Al

**Comment by GetITWorking** [comment]
do I have to install web pack? or is that installed when I do `npm i `

**Comment by GetITWorking** [comment]
I've sorted this error now, had a older version of node running (v10.0.0) , so installed version v12.0.0 and then uninstalled the older version e.g.

        nvm install v12.0.0
	nvm uninstall v10.0.0
	npm i
	npm run dev

Now I have other issues,.. but will work them out soon so I will close this now!
